logging:
  level:
    work.cxlm: DEBUG
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.hibernate.type.descriptor.sql.BasicExtractor: INFO
  file:
    path: ${user.home}/key3-dev/logs

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:6621/key3?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=UTC
    username: cxlm
    password: DB_mima~9749
  jpa:
    show-sql: true

qfzs:
  doc-disabled: false
  production-env: false
#  auth-enabled: true
  mode: development
  workDir: ${user.home}/my-font-dev/
  cache: level