server:
  port: 8520
  error:
    path: key3/error/error.ftl

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:6621/key3?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=UTC
    username: cxlm
    password: DB_mima~9749
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  profiles:
    active: dev

qfzs:
  cache: level
  version: @app_version@
  app-id: wxe431bee8e845d7e2
  app-secret: ea3d953e26b9c76b07e43b99f9c8375a
  app-request-url: "https://api.weixin.qq.com/sns/jscode2session"
  system-admin-doc: "https://cxlm.work/s/key3-system-admin-doc"
  club-admin-doc: "https://cxlm.work/s/key3-club-admin-doc"
  user-doc: "https://cxlm.work/s/key3-user-doc"
